# Generated by Django 3.2 on 2024-04-30 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240430_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referred_code',
        ),
    ]
