# Generated by Django 3.2 on 2024-04-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Vendorsubscription',
        ),
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
    ]
